name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup 
      run: |
          python3 -m pip install -U pytest
          python3 -m pip install -U -r requirements.txt

    - name: Test
      run: cd autoortho && pytest 
